"""initial schema

Revision ID: a2cf68da34bd
Revises: 
Create Date: 2026-10-02 14:48:25.341990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2cf68da34bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    "admin_users", "categories", "customers", "order_events", "order_items", "orders",
    "payment_transactions", "phone_blocklist", "product_colors", "product_images",
    "product_variants", "products", "sizes",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_users_username'))
    )
    op.create_table('categories',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('customers',
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('governorate', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('phone', name=op.f('uq_customers_phone'))
    )
    op.create_table('phone_blocklist',
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone', name=op.f('pk_phone_blocklist'))
    )
    op.create_table('sizes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=40), nullable=False),
    sa.Column('label_ar', sa.String(length=40), nullable=False),
    sa.Column('size_group', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('size_group', 'code', name='uq_sizes_group_code')
    )
    op.create_table('orders',
    sa.Column('order_number', sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('cod', 'paymob', name='payment_method'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', 'failed', 'refunded', 'partially_refunded', name='payment_status'), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('ship_full_name', sa.String(length=120), nullable=False),
    sa.Column('ship_phone', sa.String(length=11), nullable=False),
    sa.Column('ship_email', sa.String(length=254), nullable=True),
    sa.Column('ship_governorate', sa.String(length=40), nullable=False),
    sa.Column('ship_address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal_piasters', sa.Integer(), nullable=False),
    sa.Column('shipping_piasters', sa.Integer(), nullable=False),
    sa.Column('total_piasters', sa.Integer(), nullable=False),
    sa.Column('refunded_piasters', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paymob_intention_id', sa.String(length=120), nullable=True),
    sa.Column('paymob_order_id', sa.String(length=64), nullable=True),
    sa.Column('paymob_client_secret', sa.String(length=255), nullable=True),
    sa.Column('payment_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paymob_txn_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bosta_delivery_id', sa.String(length=64), nullable=True),
    sa.Column('bosta_tracking_number', sa.String(length=64), nullable=True),
    sa.Column('stock_restored', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('refunded_piasters >= 0', name=op.f('ck_orders_refunded_non_negative')),
    sa.CheckConstraint('total_piasters = subtotal_piasters + shipping_piasters', name=op.f('ck_orders_total_sum')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_ship_phone', 'orders', ['ship_phone'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('description_ar', sa.Text(), server_default='', nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('price_piasters', sa.Integer(), nullable=False),
    sa.Column('compare_at_piasters', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('compare_at_piasters IS NULL OR compare_at_piasters > price_piasters', name=op.f('ck_products_compare_at_gt_price')),
    sa.CheckConstraint('price_piasters > 0', name=op.f('ck_products_price_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index('ix_products_active_sort', 'products', ['is_active', 'sort_order'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('amount_piasters', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_transactions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('provider_txn_id', name=op.f('uq_payment_transactions_provider_txn_id'))
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_table('product_colors',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=60), nullable=False),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_colors_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_colors'))
    )
    op.create_index(op.f('ix_product_colors_product_id'), 'product_colors', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('alt_ar', sa.String(length=200), server_default='', nullable=False),
    sa.Column('width', sa.Integer(), server_default='1200', nullable=False),
    sa.Column('height', sa.Integer(), server_default='1500', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['product_colors.id'], name=op.f('fk_product_images_color_id_product_colors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('size_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('price_override_piasters', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_override_piasters IS NULL OR price_override_piasters > 0', name=op.f('ck_product_variants_override_positive')),
    sa.CheckConstraint('stock >= 0', name=op.f('ck_product_variants_stock_non_negative')),
    sa.ForeignKeyConstraint(['color_id'], ['product_colors.id'], name=op.f('fk_product_variants_color_id_product_colors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name=op.f('fk_product_variants_size_id_sizes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('product_id', 'color_id', 'size_id', name='uq_variant_combo', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_name_en', sa.String(length=160), nullable=False),
    sa.Column('product_name_ar', sa.String(length=160), nullable=False),
    sa.Column('variant_label_en', sa.String(length=120), nullable=False),
    sa.Column('variant_label_ar', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('unit_price_piasters', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_order_items_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###
    # Supabase exposes tables through its public REST API; RLS without policies
    # blocks that path entirely. The app connects as the owner role and is unaffected.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_colors_product_id'), table_name='product_colors')
    op.drop_table('product_colors')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_products_active_sort', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_ship_phone', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('sizes')
    op.drop_table('phone_blocklist')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
    for enum in ("order_status", "payment_method", "payment_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
